### ISSUE TITLE
Each member should describe the implementation of at least one enhancement he has added

### ISSUE THREAD

**Issue by luo-git** [AY2021S1-CS2103T-F12-1/tp#161]
Update the Developer Guide as follows:
Each member should describe the implementation of at least one enhancement she has added (or planning to add).
Expected length: 1+ page per person

The description can contain things such as,
* How the feature is implemented (or is going to be implemented).
* Why it is implemented that way.
* Alternatives considered.

**Comment by HynRidge** [comment]
Everyone one has contributed to DG!
