### ISSUE TITLE
Update OpenCommand to take Label

### ISSUE THREAD

**Issue by luo-git** [AY2021S1-CS2103T-F12-1/tp#180]
Open all tags with that label.

Command format example:
open l/label

**Comment by luo-git** [comment]
Open command only takes 1 label or 1 tag but not both.

**Comment by li-s** [comment]
OpenCommand should take in "Pepe Julian Onziema" and show "why are you gay meme", while opening https://www.youtube.com/watch?v=knn4iDKAO4s
