### ISSUE TITLE
Long file address results in cut off in UI

### ISSUE THREAD

**Issue by luo-git** [AY2021S1-CS2103T-F12-1/tp#89]
![image](https://user-images.githubusercontent.com/51979232/95683514-5afcc800-0c1e-11eb-92b5-7f0f65e2e97a.png)

Current UI results in cut off of address (potentially tag name too).

Would it be better to enlarge the tag view, or maybe make the pane scrollable horizontally?

**Comment by Ma-Yueran** [comment]
I am thinking about making the Ui show the details of a tag when a tag box is clicked, then there is no need to scale. Is that ok?

**Comment by Ma-Yueran** [comment]
Besides that I think I will also try to make the list scalable horizontally, I think that's a good suggestion.

**Comment by luo-git** [comment]
Yes! I think that will be good.
